#!/usr/bin/env python3
import os
import sys
import webbrowser
from getpass import getuser

import azcat

HELP = """\
azcat - A alternative to cat(1); specialized for printing files
usage: az file

options:
  --help  print this message

examples:
  $ az hello.py
  $ curl -L seiya.me/arch-setup | az

version:
  3.0
"""

def main ():
    # one program, one easter egg
    if getuser().upper() == "YUI" and os.getcwd() == "azunyan nyan nyan azunyan nyan nyan":
        print("azcat: mou!")
        webbrowser.open("http://www.pixiv.net/member_illust.php?mode=medium&illust_id=29734557")

    try:
        if sys.argv[1] == "--help":
            print(HELP)
            sys.exit()
        filepath = sys.argv[1]
    except IndexError:
        filepath = "/dev/stdin"

    if not os.path.exists(filepath):
        sys.exit("azcat: no such a file: %s" % filepath)

    azcat.main(filepath)

if __name__ == "__main__":
    main()
